#cloud-config
package_upgrade: true
package_reboot_if_required: true
ssh:
  emit_keys_to_console: false
no_ssh_fingerprints: false

groups:
  - cloud-users
  - minio-user

users:
  - name: minio-user
    primary_group: minio-user
    shell: /bin/bash
    groups:
      - cloud-users
  - name: adminuser
    primary_group: cloud-users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups:
      - sudo

packages:
  - smartmontools
  - xfsprogs
  - dnsmasq
  - prometheus-node-exporter
  - prometheus
  - git
  - update-notifier-common
  - software-properties-common
  - apt-transport-https
  - prometheus-alertmanager
  - nginx-light
  - certbot
  - prometheus-nginx-exporter
  - s3cmd
  - grub-efi-amd64

runcmd:
  - [systemctl, enable, --now, ufw]
  - [ufw, default, allow, outgoing]
  - [ufw, default, deny, incoming]
  - [ufw, allow, from, 10.0.0.0/8]
  - [ufw, limit, ssh]
  - [ufw, enable]
  - [modprobe, 8021q]
  - [rsync, -av, "/root/.ssh", /home/adminuser/]
  - [chown, -R, "adminuser:cloud-users", "/home/adminuser/"]
  - [sed, -i, -e, '/^#MaxAuthTries/s/^.*$/MaxAuthTries 5/', /etc/ssh/sshd_config]
  - [sed, -i, -e, '/^X11Forwarding/s/^.*$/X11Forwarding no/', /etc/ssh/sshd_config]
  - [systemctl, disable, --now, ssh]
  - [systemctl, enable, --now, ssh]
  - [systemctl, reset-failed]
  - [bash, /opt/equinix/metal/bin/metal_mnmd_deploy.sh]

write_files:
  - path: "/etc/modules-load.d/8021q.conf"
    permissions: "0644"
    owner: "root:root"
    append: true
    content: |
      8021q

  - path: "/etc/smartd.conf"
    permissions: "0644"
    owner: "root:root"
    append: true
    content: |
      DEVICESCAN -d auto -n standby -m <nomailer> -M exec /usr/share/smartmontools/smartd-runner

  - path: "/etc/default/smartmontools"
    permissions: "0644"
    owner: "root:root"
    append: true
    content: |
      start_smartd=yes

  - path: "/etc/ssh/sshd_config"
    permissions: "0644"
    owner: "root:root"
    append: true
    content: |
      PermitRootLogin no

  - path: "/opt/equinix/metal/bin/metal_mnmd_deploy.sh"
    permissions: "0644"
    owner: "root:root"
    append: true
    content: |
      logger "/opt/equinix/metal/bin/metal_mnmd_deploy.sh sourced / executed"
      mkdir -p /opt/equinix/metal/tmp/
      mkdir -p /opt/equinix/metal/etc/
      touch /opt/equinix/metal/etc/metal_tag_extend.env
      if test -f /opt/equinix/metal/bin/metal_mnmd_sharedlib.sh; then
        source /opt/equinix/metal/bin/metal_mnmd_sharedlib.sh
      fi
      rm -rf /opt/equinix/metal/tmp/metal_mnmd &> /dev/null
      if [ -n "$MMNMD_BRANCH" ]; then
        git clone -b $MMNMD_BRANCH https://github.com/dlotterman/metal_mnmd /opt/equinix/metal/tmp/metal_mnmd
      else
       git clone https://github.com/dlotterman/metal_mnmd /opt/equinix/metal/tmp/metal_mnmd
      fi
      if [ $? -eq 0 ]; then
        true
      else
        logger "git clone failed, exiting 1"
        exit 1
      fi
      rsync -a /opt/equinix/metal/tmp/metal_mnmd/bin/* /opt/equinix/metal/bin/
      touch /opt/equinix/metal/etc/metal_tag_extend.env
      cp /opt/equinix/metal/tmp/metal_mnmd/etc/systemd/metal_tag_extend.timer /etc/systemd/system/
      cp /opt/equinix/metal/tmp/metal_mnmd/etc/systemd/metal_tag_extend.service /etc/systemd/system/
      systemctl daemon-reload
      systemctl enable --now metal_tag_extend.timer
      systemctl start metal_tag_extend.service
      sleep 70
      bash /opt/equinix/metal/bin/metal_nvme_manage.sh
      bash /opt/equinix/metal/bin/metal_disk_setup.sh
      bash /opt/equinix/metal/bin/metal_network_setup.sh
      bash /opt/equinix/metal/bin/metal_dnsmasq_manage.sh
      bash /opt/equinix/metal/bin/metal_monitoring_mangle.sh
      bash /opt/equinix/metal/bin/minio_binary_mangle.sh
      bash /opt/equinix/metal/bin/minio_etc_manage.sh
      bash /opt/equinix/metal/bin/metal_linux_settings.sh
      bash /opt/equinix/metal/bin/minio_certs_manage.sh
      bash /opt/equinix/metal/bin/nginx_restart_manage.sh
